# Generated by Django 5.0.4 on 2024-05-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLogin', '0003_loginmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginmodel',
            table='login',
        ),
    ]
