# Generated by Django 5.0.4 on 2024-05-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLogin', '0005_alter_loginmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='cargo',
            field=models.ForeignKey(db_column='cargo_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionLogin.cargosmodel'),
        ),
    ]
